---
- name: change grub
  hosts: node
  become: true
  tasks:
  - name: change /etc/default/grub
    ansible.builtin.lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*net\.ifnames)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'
      state: present
      backrefs: yes
    notify: Write grub configuration file
  
  - name: change /etc/default/grub
    ansible.builtin.lineinfile:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
      state: present
      backrefs: yes
    notify: Write grub configuration file

  handlers:
  - name: Write grub configuration file
    command: grub2-mkconfig -o /boot/grub2/grub.cfg

