---
- name: Create users
  hosts: test
  gather_facts: false
      
  vars_files:
    - users_pass.yml

  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{ item.user }}"
        comment: "{{ item.user }}@example.com"
        home: "/home/{{ item.user }}"
        password: "{{ item.pass | string | password_hash('sha512') }}"
        update_password: on_create
      become: yes
      with_items:
        - "{{ newusers }}"