---
- name: Create users
  hosts: node
  gather_facts: false
      
  vars_files:
    - users_pass.yml
    - users_name.yml

  tasks:
    - ansible.builtin.user:
        name: "{{ item }}"
        comment: "{{ item }}@example.com"
        home: "/home/{{ item }}"
        password: "{{ passwords[item] | password_hash('sha512') }}"
        update_password: on_create
      become: yes
      with_items:
        - "{{ users }}"