---
# tasks file for vsftpd
- name: install vsftpd
  ansible.builtin.yum:
    name: vsftpd
    state: present
  notify: reload vsftpd
  when:
    - ansible_distribution == "{{ os }}"

- name: copy vsftpd.conf
  ansible.builtin.template:
    src: vsftpd.conf.j2
    dest: "{{ project_root }}/vsftpd.conf"
    owner: root
    group: root
    mode: 0600
  notify: reload vsftpd

- name: Enable service to start
  ansible.builtin.service:
    name: vsftpd
    enabled: yes
  notify: reload vsftpd

- name: changed permission
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0755"
  notify: reload vsftpd
  loop:
    - { path: '/var/ftp/pub', name: 'nobody' }
    - { path: '/var/ftp/pub/upload', name: 'ftp' }

- name: install semanage 'python3-libsemanage'
  ansible.builtin.yum:
    name: python3-libsemanage
    state: present
  when:
    - ansible_distribution == "{{ os }}"

- name: setsebool
  seboolean:
    name: allow_ftpd_anon_write
    state: yes
    persistent: yes

- name: Run command chcon
  ansible.builtin.command: chcon -t public_content_rw_t /var/ftp/pub/upload

- name: Configure firewall to allow ftp
  firewalld:
    service: "ftp"
    permanent: yes
    state: enabled
  notify: reload firewalld
